# -*- coding: utf-8 -*-
"""article_inep_notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CaEaklzP58oiO3wKuz11KwGB09P8IX9o

## importação de libs relevantes
"""

import pandas as pd
import statsmodels.api as sm
from sklearn.preprocessing import PowerTransformer
import numpy as np

def get_vif(df, reg_cols):
  mc_df = []
  df.dropna(inplace=True)
  for col in reg_cols:
    x = sm.add_constant(df[reg_cols].drop(columns=col))
    y = df[col]
    model = sm.OLS(y, x).fit()
    mc_df.append({
        'variável':col,
        'R²':model.rsquared,
        'VIF':1/(1-model.rsquared)
    })

  return pd.DataFrame(mc_df)

"""Importação de bases de dados e remoção da coluna <code>ANO</code> (irrelevante ao modelo)"""

df_censo_escolar_2017 = pd.read_csv('/content/microdados_ed_basica_2017.csv', encoding='ISO-8859-1', sep=';', on_bad_lines='skip')

df_tx_ev_rep = pd.read_excel('/content/TX_REP_EV_2017_2018.xlsx')
df_tx_ev_rep = df_tx_ev_rep.drop(columns=['ANO'])

df_tx_dist_idade = pd.read_excel('/content/TX_DISTORCAO_IDADE_MUNICIPIOS_2017.xlsx')
df_tx_dist_idade = df_tx_dist_idade.drop(columns=['ANO'])

df_esfor_docente = pd.read_excel('/content/IEsforcoD_MUNICIPIOS_2017.xlsx')
df_esfor_docente = df_esfor_docente.drop(columns=['ANO'])

df_alun_por_turma = pd.read_excel('/content/ALUNOS_POR_TURMA_MUNICIPIOS_2017.xlsx')
df_alun_por_turma = df_alun_por_turma.drop(columns=['ANO'])

df_adeq_formacao_docente = pd.read_excel('/content/ADEQ_FORMAÇÃO_DOCENTE_MUNICIPIOS_2017.xlsx')
df_adeq_formacao_docente = df_adeq_formacao_docente.drop(columns=['ANO'])

"""Definição das coluna-chave e que se repetem em todas as bases de dados; join nas base de dados importadas acima"""

common_keys = ['NOME_MUNICIPIO', 'UF', 'COD_MUNICIPIO', 'DEP_ADMINISTRATIVA', 'REGIAO', 'LOCALIZACAO']

df_joined = (pd.merge(df_tx_ev_rep, df_tx_dist_idade, how='inner', on=common_keys)
.merge(df_esfor_docente, how='inner', on=common_keys)
.merge(df_alun_por_turma, how='inner', on=common_keys)
.merge(df_adeq_formacao_docente, how='inner', on=common_keys))

len(df_joined['COD_MUNICIPIO'].unique())

"""Constatação das colunas, valores nulos e seus tipos após o join"""

df_joined.info()

"""A fim de não causar ruído no modelo, filtra-se apenas pelos tipos de depêndencia adiministrativa que não são 'Total'

concomitamente remove-se a coluna <code>NOME_MUNICIPIO</code> deviso sua irrelevância para a regressão
"""

df_joined = df_joined[(df_joined['DEP_ADMINISTRATIVA'] != 'Total')]

df_joined

df_joined.info()

#df_joined = df_joined.drop(columns=['NOME_MUNICIPIO'])

"""Tabela de correlação de Pearson preliminar das bases mescladas"""

for col in df_joined.select_dtypes(include='number').columns.difference(['COD_MUNICIPIO', 'NUM_ALUNO_TURMA_TOTAL', 'NOME_MUNICIPIO']).tolist():
  df_joined[col] = df_joined[col]/100

"""remoção de linhas NaN com base na coluna <code>COD_MUNICIPIO</code>"""

df_joined.dropna(inplace=True)

df_inep_model = df_joined.copy()

df_inep_model = pd.get_dummies(df_inep_model, columns=['DEP_ADMINISTRATIVA'], drop_first=True)
df_inep_model['DEP_ADMINISTRATIVA_Pública'] = df_inep_model['DEP_ADMINISTRATIVA_Pública'].astype(int)

selected_cols = df_inep_model.columns.difference(['COD_MUNICIPIO', 'NOME_MUNICIPIO', 'REGIAO', 'UF', 'LOCALIZACAO']).tolist()

df_inep_model.info()

selected_cols_prime = [
    'TX_REP_TOTAL',
    'TX_DI_TOTAL',
    'NUM_ALUNO_TURMA_TOTAL',
    'DEP_ADMINISTRATIVA_Pública',
  'TX_IED_N1','TX_IED_N2','TX_IED_N3', 'TX_IED_N4', 'TX_IED_N5', 'TX_IED_N6',
   'Grupo 1','Grupo 2', 'Grupo 3', 'Grupo 4', 'Grupo 5'
]
df_inep_prime = df_inep_model[selected_cols_prime]
vif_display = get_vif(df_inep_prime, reg_cols=selected_cols_prime)
vif_display

selected_cols = [
    'COD_MUNICIPIO',
    'NOME_MUNICIPIO',
    'TX_REP_TOTAL',
    'TX_EV_TOTAL',
    'TX_DI_TOTAL',
    'NUM_ALUNO_TURMA_TOTAL',
    'DEP_ADMINISTRATIVA_Pública',
  'TX_IED_N3', 'TX_IED_N4', 'TX_IED_N5', 'TX_IED_N6',
   'Grupo 2', 'Grupo 3', 'Grupo 4', 'Grupo 5'
]
df_inep_model = df_inep_model[selected_cols]

selected_cols.pop(0)
selected_cols.pop(0)
selected_cols.pop(1)

vif_display = get_vif(df_inep_model, reg_cols=selected_cols)
vif_display

df_censo_escolar_2017.columns

"""Seleção das colunas que serão filtradas da base de dados censo escolar do inep"""

main_columns = ['CO_MUNICIPIO',
                'NO_MUNICIPIO',
                'SG_UF',
                'NO_REGIAO',
                'IN_BIBLIOTECA',
                'IN_COZINHA',
                'IN_LABORATORIO_CIENCIAS',
                'IN_LABORATORIO_INFORMATICA',
                'IN_QUADRA_ESPORTES',
                'IN_ACESSIBILIDADE_ELEVADOR',
                'IN_PROF_PSICOLOGO',
                'IN_INTERNET',
                'IN_DESKTOP_ALUNO',
                'IN_COMP_PORTATIL_ALUNO',
                'IN_INTERNET_ALUNOS',
                'IN_EXAME_SELECAO',
                'TP_DEPENDENCIA', #1~3 pública; 4 privada
                ]

df_selecionado_censo = df_censo_escolar_2017.loc[:, main_columns]

"""Vista das colunas filtradas, seus tipos e valores nulos"""

df_selecionado_censo.info()

"""Transformação do tipo de dependência administrativa. De int para string"""

df_selecionado_censo.loc[(df_selecionado_censo['TP_DEPENDENCIA'] == 1) | (df_selecionado_censo['TP_DEPENDENCIA'] == 2) | (df_selecionado_censo['TP_DEPENDENCIA'] == 3), 'TP_DEPENDENCIA'] = 'Pública'

df_selecionado_censo.loc[(df_selecionado_censo['TP_DEPENDENCIA'] == 4), 'TP_DEPENDENCIA'] = 'Privada'

"""Renomeação de colunas para o nome padronizado nas demais bases de dados do inep"""

df_selecionado_censo = df_selecionado_censo.rename(columns={'SG_UF':'UF', 'CO_MUNICIPIO':'COD_MUNICIPIO', 'TP_LOCALIZACAO':'LOCALIZACAO', 'TP_DEPENDENCIA':'DEP_ADMINISTRATIVA', 'NO_REGIAO':'REGIAO', 'NO_MUNICIPIO':'NOME_MUNICIPIO'})

"""Agrupamento pelas colunas do tipo object"""

df_grouped = df_selecionado_censo.groupby(by=['COD_MUNICIPIO', 'DEP_ADMINISTRATIVA', 'REGIAO', 'UF', 'NOME_MUNICIPIO'], as_index=False).sum()

df_count = df_selecionado_censo.groupby(by=['COD_MUNICIPIO', 'DEP_ADMINISTRATIVA', 'REGIAO', 'UF', 'NOME_MUNICIPIO'], as_index=False)['COD_MUNICIPIO'].count()

"""Transforção dos valores em taxas no formato decimal"""

col_list = df_grouped.select_dtypes(include='number').columns.tolist()
col_list.pop(0)

print(col_list)

for col in col_list:
  df_grouped[col] = (df_grouped[col]/df_count['COD_MUNICIPIO'])

df_joined['COD_MUNICIPIO'] = df_joined['COD_MUNICIPIO'].astype('int64')

df_grouped = pd.get_dummies(df_grouped, columns=['DEP_ADMINISTRATIVA'], drop_first=True)
df_grouped = df_grouped.drop(columns=['REGIAO', 'UF'])

df_grouped.dropna(inplace=True)

df_grouped['DEP_ADMINISTRATIVA_Pública'] = df_grouped['DEP_ADMINISTRATIVA_Pública'].astype(int)

df_grouped.info()

len(df_grouped['COD_MUNICIPIO'].unique())

"""## Join com as base de dados anteriores"""

df_model = pd.merge(df_inep_model, df_grouped, how='inner', on=['COD_MUNICIPIO', 'DEP_ADMINISTRATIVA_Pública', 'NOME_MUNICIPIO'])

df_model

get_vif(df_model, reg_cols=df_model.columns.difference(['COD_MUNICIPIO', 'NOME_MUNICIPIO']).tolist())

df_model.drop(columns=['IN_ACESSIBILIDADE_ELEVADOR', 'IN_COMP_PORTATIL_ALUNO', 'IN_DESKTOP_ALUNO', 'IN_EXAME_SELECAO', 'IN_INTERNET_ALUNOS', 'IN_PROF_PSICOLOGO'], inplace=True)

df_model['TX_EV_TOTAL'].skew()

df_model = df_model.dropna()

'''pt = PowerTransformer(standardize=False, method='yeo-johnson')
x = df_model[df_model.columns.difference(['COD_MUNICIPIO', 'TX_EV_TOTAL']).tolist()]
x_t = pt.fit_transform(x)
x = pd.DataFrame(x_t, columns=x.columns)'''

x = (df_model[df_model.columns.difference(['COD_MUNICIPIO', 'TX_EV_TOTAL', 'NOME_MUNICIPIO']).tolist()])
y = (df_model['TX_EV_TOTAL'])

vif = get_vif(df_model, reg_cols=df_model.columns.difference(['COD_MUNICIPIO', 'TX_EV_TOTAL', 'NOME_MUNICIPIO']).tolist())
vif

def get_model(x, y):
  x = sm.add_constant(x)
  model = sm.OLS(y, x).fit()
  return model

df_model.info()

len(df_model['COD_MUNICIPIO'].unique())

ols_model = get_model(x=x, y=y)

ols_model.summary()

df_model.corr(numeric_only=True).to_latex()

q1 = df_model['TX_EV_TOTAL'].quantile(0.25)
q3 = df_model['TX_EV_TOTAL'].quantile(0.75)

iqr = q3 - q1

sup_outlier_threshold = q3 + 1.5*iqr

print(sup_outlier_threshold)
print(df_model['TX_EV_TOTAL'].quantile(0.25))
print(df_model['TX_EV_TOTAL'].quantile(0.5))
print(df_model['TX_EV_TOTAL'].quantile(0.75))

no_outliers_df_model = df_model[df_model['TX_EV_TOTAL'] <= sup_outlier_threshold]

x = no_outliers_df_model[df_model.columns.difference(['COD_MUNICIPIO', 'TX_EV_TOTAL', 'NOME_MUNICIPIO']).tolist()]
y = no_outliers_df_model['TX_EV_TOTAL']
no_outliers_model = get_model(x=x, y=y)
no_outliers_model.summary()

outliers_df_model = df_model[df_model['TX_EV_TOTAL'] > sup_outlier_threshold]

x = outliers_df_model[df_model.columns.difference(['COD_MUNICIPIO', 'TX_EV_TOTAL', 'NOME_MUNICIPIO']).tolist()]
y = outliers_df_model['TX_EV_TOTAL']
outliers_model = get_model(x=x, y=y)
outliers_model.summary()

import matplotlib.pyplot as plt

dados = df_model['TX_EV_TOTAL']

plt.boxplot(dados)
plt.title('Distribuição da Variável TX_EV_TOTAL')
plt.ylabel("Taxa")
plt.show()

dados.to_excel('boxplot_tx_ev_total.xlsx', index=False, header=True)

plt.hist(x=df_model['TX_REP_TOTAL'], bins=30)
plt.title('Histograma TX_REP_TOTAL')
plt.xlabel('Taxa')
plt.ylabel('Frequência')
plt.show()

df_model['TX_REP_TOTAL'].to_excel('histograma_tx_rep_total.xlsx', header=True, index=False)

plt.hist(x=df_model['TX_DI_TOTAL'], bins=30)
plt.title('Histograma TX_DI_TOTAL')
plt.xlabel('Taxa')
plt.ylabel('Frequência')
plt.show()

df_model['TX_DI_TOTAL'].to_excel('histograma_tx_di_total.xlsx', header=True, index=False)

ols_model.mse_total

df_model_bimodal_test = df_model.copy()

df_model_bimodal_test['TX_DI_GRUPO_1'] = 0
df_model_bimodal_test.loc[df_model_bimodal_test['TX_DI_TOTAL'] >= 0.2, 'TX_DI_GRUPO_1'] = 1

df_model_bimodal_test_no = df_model_bimodal_test[df_model_bimodal_test['TX_EV_TOTAL'] <= sup_outlier_threshold]
df_model_bimodal_test_no

x = df_model_bimodal_test_no[df_model_bimodal_test.columns.difference(['COD_MUNICIPIO', 'TX_EV_TOTAL', 'NOME_MUNICIPIO', 'TX_DI_TOTAL']).tolist()]
y = df_model_bimodal_test_no['TX_EV_TOTAL']
model_bimodal_no = get_model(x=x, y=y)
model_bimodal_no.summary()

df_model_bimodal_test_o = df_model_bimodal_test[df_model_bimodal_test['TX_EV_TOTAL'] > sup_outlier_threshold]
df_model_bimodal_test_o

exc_cols = [
    'COD_MUNICIPIO',
    'TX_EV_TOTAL',
    'NOME_MUNICIPIO',
    'TX_DI_TOTAL',
    'Grupo 2',
    'Grupo 3',
    'Grupo 4',
    'Grupo 5',
    'IN_BIBLIOTECA',
    'IN_COZINHA',
    'IN_INTERNET',
    'IN_LABORATORIO_CIENCIAS',
    'IN_QUADRA_ESPORTES',
    'NUM_ALUNO_TURMA_TOTAL',
    'TX_IED_N3',
    'TX_IED_N4',
    'TX_IED_N5',
    'TX_IED_N6'
    ]

x = df_model_bimodal_test_o[df_model_bimodal_test.columns.difference(['COD_MUNICIPIO', 'TX_EV_TOTAL', 'NOME_MUNICIPIO', 'TX_DI_TOTAL']).tolist()]
y = df_model_bimodal_test_o['TX_EV_TOTAL']
model_bimodal_no = get_model(x=x, y=y)
model_bimodal_no.summary()

x = df_model_bimodal_test_o[df_model_bimodal_test.columns.difference(exc_cols).tolist()]
y = df_model_bimodal_test_o['TX_EV_TOTAL']
model_bimodal_no = get_model(x=x, y=y)
model_bimodal_no.summary()

df_saeb = pd.read_csv('/content/TS_ALUNO_3EM_AG.csv')

saeb_cols = [
    'ID_ESCOLA',
    'PROFICIENCIA_LP',
    'PROFICIENCIA_MT',
    'TX_RESP_Q052',
    'TX_RESP_Q027',
    'TX_RESP_Q044',
    'TX_RESP_Q001',
    'TX_RESP_Q002',
    'TX_RESP_Q038',
    'TX_RESP_Q041'
]

df_saeb = df_saeb[saeb_cols]

df_saeb.loc[df_saeb['TX_RESP_Q052'] == 'A', 'TX_RESP_Q052'] = 1
df_saeb.loc[df_saeb['TX_RESP_Q052'] == 'B', 'TX_RESP_Q052'] = 0

df_saeb.loc[df_saeb['TX_RESP_Q027'] == 'A', 'TX_RESP_Q027'] = 1
df_saeb.loc[df_saeb['TX_RESP_Q027'] == 'B', 'TX_RESP_Q027'] = 0

df_saeb.loc[df_saeb['TX_RESP_Q038'] == 'A', 'TX_RESP_Q038'] = 1
df_saeb.loc[df_saeb['TX_RESP_Q038'] == 'B', 'TX_RESP_Q038'] = 0

df_saeb.loc[df_saeb['TX_RESP_Q041'] == 'A', 'TX_RESP_Q041'] = 0
df_saeb.loc[df_saeb['TX_RESP_Q041'] == 'B', 'TX_RESP_Q041'] = 1
df_saeb.loc[df_saeb['TX_RESP_Q041'] == 'C', 'TX_RESP_Q041'] = 1

df_saeb.loc[df_saeb['TX_RESP_Q044'] == 'A', 'TX_RESP_Q044'] = 1
df_saeb.loc[df_saeb['TX_RESP_Q044'] == 'B', 'TX_RESP_Q044'] = 0

df_saeb.loc[df_saeb['TX_RESP_Q002'] == 'A', 'TX_RESP_Q002'] = 'Branca'
df_saeb.loc[df_saeb['TX_RESP_Q002'] == 'B', 'TX_RESP_Q002'] = 'Preta'
df_saeb.loc[df_saeb['TX_RESP_Q002'] == 'C', 'TX_RESP_Q002'] = 'Parda'
df_saeb.loc[df_saeb['TX_RESP_Q002'] == 'D', 'TX_RESP_Q002'] = 'Amarelo'
df_saeb.loc[df_saeb['TX_RESP_Q002'] == 'E', 'TX_RESP_Q002'] = 'Indígena'
df_saeb.loc[df_saeb['TX_RESP_Q002'] == 'F', 'TX_RESP_Q002'] = None

df_saeb.loc[df_saeb['TX_RESP_Q001'] == 'A', 'TX_RESP_Q001'] = 1
df_saeb.loc[df_saeb['TX_RESP_Q001'] == 'B', 'TX_RESP_Q001'] = 0

'''df_saeb.loc[df_saeb['ID_UF'] == 11, 'ID_UF'] = 'RO'
df_saeb.loc[df_saeb['ID_UF'] == 12, 'ID_UF'] = 'AC'
df_saeb.loc[df_saeb['ID_UF'] == 13, 'ID_UF'] = 'AM'
df_saeb.loc[df_saeb['ID_UF'] == 14, 'ID_UF'] = 'RR'
df_saeb.loc[df_saeb['ID_UF'] == 15, 'ID_UF'] = 'PA'
df_saeb.loc[df_saeb['ID_UF'] == 16, 'ID_UF'] = 'AP'
df_saeb.loc[df_saeb['ID_UF'] == 17, 'ID_UF'] = 'TO'
df_saeb.loc[df_saeb['ID_UF'] == 21, 'ID_UF'] = 'MA'
df_saeb.loc[df_saeb['ID_UF'] == 22, 'ID_UF'] = 'PI'
df_saeb.loc[df_saeb['ID_UF'] == 23, 'ID_UF'] = 'CE'
df_saeb.loc[df_saeb['ID_UF'] == 24, 'ID_UF'] = 'RN'
df_saeb.loc[df_saeb['ID_UF'] == 25, 'ID_UF'] = 'PB'
df_saeb.loc[df_saeb['ID_UF'] == 26, 'ID_UF'] = 'PE'
df_saeb.loc[df_saeb['ID_UF'] == 27, 'ID_UF'] = 'AL'
df_saeb.loc[df_saeb['ID_UF'] == 28, 'ID_UF'] = 'SE'
df_saeb.loc[df_saeb['ID_UF'] == 29, 'ID_UF'] = 'BA'
df_saeb.loc[df_saeb['ID_UF'] == 31, 'ID_UF'] = 'MG'
df_saeb.loc[df_saeb['ID_UF'] == 32, 'ID_UF'] = 'ES'
df_saeb.loc[df_saeb['ID_UF'] == 33, 'ID_UF'] = 'RJ'
df_saeb.loc[df_saeb['ID_UF'] == 35, 'ID_UF'] = 'SP'
df_saeb.loc[df_saeb['ID_UF'] == 41, 'ID_UF'] = 'PR'
df_saeb.loc[df_saeb['ID_UF'] == 42, 'ID_UF'] = 'SC'
df_saeb.loc[df_saeb['ID_UF'] == 43, 'ID_UF'] = 'RS'
df_saeb.loc[df_saeb['ID_UF'] == 50, 'ID_UF'] = 'MS'
df_saeb.loc[df_saeb['ID_UF'] == 51, 'ID_UF'] = 'MT'
df_saeb.loc[df_saeb['ID_UF'] == 52, 'ID_UF'] = 'GO'
df_saeb.loc[df_saeb['ID_UF'] == 53, 'ID_UF'] = 'DF'

'''

df_saeb = pd.get_dummies(df_saeb, columns=['TX_RESP_Q002'])

df_saeb

df_saeb.dropna(inplace=True)

for bool_col in df_saeb.select_dtypes(include='bool').columns.tolist():
  df_saeb[bool_col] = df_saeb[bool_col].astype(int)

df_saeb

df_saeb.info()

obj_to_num_cols = ['TX_RESP_Q052', 'TX_RESP_Q044', 'TX_RESP_Q001', 'TX_RESP_Q044', 'TX_RESP_Q038', 'TX_RESP_Q041', 'TX_RESP_Q027']

for col in obj_to_num_cols:
  df_saeb[col] = df_saeb[col].astype(int)

df_saeb_ag_esc = df_saeb.groupby(by=['ID_ESCOLA'], as_index=False).sum()

df_saeb_count_answers = df_saeb.groupby(by=['ID_ESCOLA'], as_index=False)['ID_ESCOLA'].count()

for col in df_saeb_ag_esc.select_dtypes(include='number').columns.difference(['ID_ESCOLA']).tolist():
  df_saeb_ag_esc[col] = df_saeb_ag_esc[col]/df_saeb_count_answers['ID_ESCOLA']

df_saeb_ag_esc

get_vif(df_saeb_ag_esc, reg_cols=df_saeb_ag_esc.select_dtypes(include='number').columns.difference(['ID_ESCOLA']).tolist())

df_saeb_ag_esc = df_saeb_ag_esc.drop(columns=['TX_RESP_Q002_Branca', 'TX_RESP_Q002_Amarelo'])

get_vif(df_saeb_ag_esc, reg_cols=df_saeb_ag_esc.select_dtypes(include='number').columns.difference(['ID_ESCOLA']).tolist())

df_saeb_ag_esc.drop(columns=['PROFICIENCIA_LP'], inplace=True)

get_vif(df_saeb_ag_esc, reg_cols=df_saeb_ag_esc.select_dtypes(include='number').columns.difference(['ID_ESCOLA']).tolist())

pt = PowerTransformer(standardize=False, method='yeo-johnson')
df_saeb_t = pt.fit_transform(df_saeb_ag_esc)
df_saeb_t = pd.DataFrame(df_saeb_t, columns=df_saeb_ag_esc.columns)

x = df_saeb_ag_esc[df_saeb_ag_esc.select_dtypes(include='number').columns.difference(['ID_ESCOLA', 'TX_RESP_Q041']).tolist()]
y = df_saeb_ag_esc['TX_RESP_Q041']

saeb_ols_model = get_model(x=x, y=y)

saeb_ols_model.summary()

saeb_ols_model.mse_total